DroneTaxi/dronetaxi/dronetaxi/dronetaxi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

DroneTaxi/dronetaxi/dronetaxi/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

DroneTaxi/dronetaxi/urls.py
from django.contrib import admin
from login import views
from django.urls import path, include

handler404 = views.Custom_handler404
urlpatterns = [
    path('registration', views.registration, name='registration'),
    path('', views.login),
    path('login', views.login, name='login'),
    path('profile/', views.profile),
    path('admin/', admin.site.urls),
    path('myorders/', views.myorders),
    path('userslist/', views.userslist),
    path('droneslist/', views.droneslist),
    path('editprofile/', views.editprofile),
    path('droneedit/', views.droneedit),
    path('orderedit/', views.orderedit),
    path('orderadd/', views.orderadd),
    path('useradd/', views.useradd),
    path('droneadd/', views.droneadd),
]

DroneTaxi/dronetaxi/login/models.py
from django.db import models


class User(models.Model):
    email = models.CharField(primary_key=True, max_length=255)
    password = models.CharField(max_length=255)
    lastname = models.CharField(max_length=64)
    firstname = models.CharField(max_length=64)
    patronymic = models.CharField(max_length=64)
    phone_number = models.CharField(max_length=20, blank=True)
    STATUS = (('adm', 'Администратор'), ('clt', 'Клиент'), ('opr', 'Оператор'))
    user_role = models.CharField(max_length=3, choices=STATUS, default='clt', verbose_name="Роль пользователя")

    class Meta:
        ordering = ['email']
        verbose_name = 'Аккаунт пользователя'
        verbose_name_plural = "Аккаунты пользователей"

    def __str__(self):
        return f'{self.email}'


class Drone(models.Model):
    drone_brand = models.CharField(max_length=150)
    drone_model = models.CharField(max_length=150)
    production_year = models.IntegerField(default=2020)
    registration_number = models.CharField(max_length=8)
    registration_date = models.DateField(verbose_name="Дата регистрации")
    STATUS = (('fre', 'Свободен'), ('bsy', 'Занят'), ('wri', 'Списан'))
    drone_status = models.CharField(max_length=3, choices=STATUS, default='fre', verbose_name="Статус дрона")
    drone_image = models.ImageField(upload_to="static/image", verbose_name="Фото дрона")
    CLASS = (('eco', 'Эконом'), ('bus', 'Бизнес'), ('pre', 'Премиум'))
    drone_class = models.CharField(max_length=3, choices=CLASS, default='eco', verbose_name='Класс дрона')

    class Meta:
        verbose_name = 'Дрон'
        verbose_name_plural = "Дроны"

    def __str__(self):
        return f'{self.drone_brand}'


class Order(models.Model):
    order_time = models.DateTimeField(verbose_name="Дата заказа")
    departure_point = models.CharField(max_length=255)
    arrival_place = models.CharField(max_length=255)
    cost = models.FloatField(verbose_name='Стоимость заказа')
    STATUS = (('can', 'Отменен'), ('cls', 'Закрыт'), ('per', 'Исполняется'), ('act', 'Активен'))
    order_status = models.CharField(max_length=3, choices=STATUS, default='act', verbose_name="Статус заказа")
    CLASS = (('eco', 'Эконом'), ('bus', 'Бизнес'), ('pre', 'Премиум'))
    drone_class = models.CharField(max_length=3, choices=CLASS, default='eco', verbose_name='Класс дрона')
    client = models.ForeignKey(User, on_delete=models.CASCADE, related_name='client')
    drone = models.ForeignKey(Drone, on_delete=models.CASCADE, blank=True, null=True)
    operator = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f'{self.client} {self.order_status}'

DroneTaxi/dronetaxi/login/forms.py
from django import forms


class UserForm(forms.Form):
    login = forms.CharField(label='Логин', label_suffix='')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль', label_suffix='')


class RegForm(forms.Form):
    lastname = forms.CharField(label='Фамилия *', label_suffix='')
    firstname = forms.CharField(label='Имя *', label_suffix='')
    patronymic = forms.CharField(label='Отчество *', label_suffix='')
    email = forms.CharField(label='Email *', label_suffix='')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль *', label_suffix='')
    confpassword = forms.CharField(widget=forms.PasswordInput, label='Подтвердить пароль *', label_suffix='')

DroneTaxi/login/forms.py
from django import forms


class UserForm(forms.Form):
    login = forms.CharField(label='Логин', label_suffix='')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль', label_suffix='')


class RegForm(forms.Form):
    lastname = forms.CharField(label='Фамилия *', label_suffix='')
    firstname = forms.CharField(label='Имя *', label_suffix='')
    patronymic = forms.CharField(label='Отчество *', label_suffix='')
    email = forms.CharField(label='Email *', label_suffix='')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль *', label_suffix='')
    confpassword = forms.CharField(widget=forms.PasswordInput, label='Подтвердить пароль *', label_suffix='')

DroneTaxi/dronetaxi/login/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound
from .forms import UserForm
from .models import User
from django.views import View
from . import services
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from datetime import datetime


class UseraccountViewSet(View):
    queryset = User.objects.all()


def login(request):
    if request.method == "POST":
        entered_email = request.POST.get("login")
        entered_password = request.POST.get("password")
        entered_rem = request.POST.get("remember")

        user = services.login_user(entered_email, entered_password)
        if user is not None:
            request.session['email'] = entered_email
            request.session['role'] = services.getuserrole(entered_email)
            request.session['remember'] = entered_rem
            return HttpResponseRedirect("/profile")
        else:

            return render(request, "login/login.html", {"error": True, "login": entered_email})
    else:

        if request.session.get('remember') == 'on':
            log = request.session['email']
            request.session['email'] = ''
        else:
            log = ''
            request.session['email'] = ''

        return render(request, "login/login.html", {"login": log})


def registration(request):
    if request.method == "GET":
        return render(request, "login/registration.html")
    if request.method == "POST":
        entered_lastname = request.POST.get("lastname")
        entered_firstname = request.POST.get("firstname")
        entered_patronymic = request.POST.get("patronymic")
        entered_email = request.POST.get("email")
        entered_password = request.POST.get("password")
        entered_confpassword = request.POST.get("confpassword")
        user = services.registration(entered_lastname, entered_firstname, entered_patronymic, entered_email,
                                     entered_password, entered_confpassword)
        if user == "mailerror":
            return render(request, "login/registration.html",
                          {"mailerror": True, "lastname": entered_lastname, "firstname": entered_firstname,
                           "patronymic": entered_patronymic,
                           "email": entered_email, "password": entered_password, "confpassword": entered_confpassword})
        if user == "passerror":
            return render(request, "login/registration.html",
                          {"passerror": True, "lastname": entered_lastname, "firstname": entered_firstname,
                           "patronymic": entered_patronymic,
                           "email": entered_email, "password": entered_password, "confpassword": entered_confpassword})
        if user == "notmail":
            return render(request, "login/registration.html",
                          {"notmail": True, "lastname": entered_lastname, "firstname": entered_firstname,
                           "patronymic": entered_patronymic,
                           "email": entered_email, "password": entered_password, "confpassword": entered_confpassword})
        if user == "smallpass":
            return render(request, "login/registration.html",
                          {"smallpass": True, "lastname": entered_lastname, "firstname": entered_firstname,
                           "patronymic": entered_patronymic,
                           "email": entered_email, "password": entered_password, "confpassword": entered_confpassword})

        request.session['email'] = entered_email
        request.session['role'] = 'clt'
        return HttpResponseRedirect("/profile")


def profile(request):
    email = request.session.get('email')
    role = request.session.get('role')
    if email is not None:
        try:
            serialized_user = email
            user = services.getUserWithEmail(serialized_user)
        except User.DoesNotExist:
            return HttpResponseRedirect("/login")

        data_context = {"user_context": serialized_user, "user": user, "role": role, "title": "Drone Taxi - Профиль"}
        return render(request, "userprofile/profile.html", context=data_context)
    else:
        return HttpResponseRedirect("/login")


def myorders(request):
    email = request.session.get('email')
    role = request.session.get('role')
    if email is not None:
        try:
            serialized_user = email
            orders = services.orderslist(serialized_user)
        except User.DoesNotExist:
            return HttpResponseRedirect("/login")
        paginator = Paginator(orders, 5)

        page = request.GET.get('page')
        try:
            orders = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            orders = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            orders = paginator.page(paginator.num_pages)
        count = len(orders)
        data_context = {"user_context": serialized_user, "orders": orders, "role": role, "count": count,
                        "title": "Drone Taxi - Мои заказы"}
        return render(request, "order/orderlist.html", context=data_context)
    else:
        return HttpResponseRedirect("/login")


def userslist(request):
    email = request.session.get('email')
    role = request.session.get('role')
    if email is not None:
        if role != 'adm':
            return HttpResponseRedirect("/profile")
        try:
            serialized_user = email
            users = services.userslist()
        except User.DoesNotExist:
            return HttpResponseRedirect("/login")
        paginator = Paginator(users, 5)

        page = request.GET.get('page')
        try:
            users = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            users = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            users = paginator.page(paginator.num_pages)

        data_context = {"user_context": serialized_user, "users": users, "role": role,
                        "title": "Drone Taxi - Список пользователей"}
        return render(request, "userprofile/userlist.html", context=data_context)
    else:
        return HttpResponseRedirect("/login")


def droneslist(request):
    email = request.session.get('email')
    role = request.session.get('role')
    if email is not None:
        if role == 'clt':
            return HttpResponseRedirect("/profile")
        try:
            serialized_user = email
            drones = services.droneslist()
        except User.DoesNotExist:
            return HttpResponseRedirect("/login")
        paginator = Paginator(drones, 4)

        page = request.GET.get('page')
        try:
            drones = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            drones = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            drones = paginator.page(paginator.num_pages)
        count = len(drones)
        data_context = {"user_context": serialized_user, "drones": drones, "role": role, "count": count,
                        "title": "Drone Taxi - Список дронов"}
        return render(request, "drone/dronelist.html", context=data_context)
    else:
        return HttpResponseRedirect("/login")


def orderedit(request):
    email = request.session.get('email')
    role = request.session.get('role')
    try:
        if email is not None:
            serialized_user = email
            if request.method == "POST":
                val = request.POST.get("addval")
                if val is not None:
                    order_id = request.POST.get("orderid")
                    entered_order_status = request.POST.get("order_status")
                    if entered_order_status == 'Отменен':
                        entered_order_status = 'can'
                    elif entered_order_status == 'Закрыт':
                        entered_order_status = 'cls'
                    elif entered_order_status == 'Исполняется':
                        entered_order_status = 'per'
                    elif entered_order_status == 'Активен':
                        entered_order_status = 'act'
                    entered_drone = request.POST.get("drone")
                    if entered_drone is not None:
                        services.orderedit(order_id, entered_order_status, entered_drone)
                    else:
                        services.orderupdate(order_id, entered_order_status)

                    return HttpResponseRedirect("/myorders")
                else:
                    order_id = request.POST.get("orderid")
                    order = services.orderinfo(order_id, serialized_user)
                    freedrones = services.freedronelist(order_id)
                    data_context = {"user_context": serialized_user, "order": order, "role": role,
                                    "freedrones": freedrones, "title": "Drone Taxi - Редактирование заказа"}
                    return render(request, "order/orderedit.html", context=data_context)
        else:
            return HttpResponseRedirect("/login")
    except User.DoesNotExist:
        return HttpResponseRedirect("/login")


def droneedit(request):
    email = request.session.get('email')
    role = request.session.get('role')
    try:
        if email is not None:
            serialized_user = email
            if role != 'adm':
                return HttpResponseRedirect("/profile")

            if request.method == "POST":
                val = request.POST.get("addval")
                if val is not None:
                    drone_id = request.POST.get("droneid")

DroneTaxi/templates/login/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <title>Drone Taxi - Аутентификация</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
</head>
<body class="BodyBackground" style="background-image: url('{% static "img/flying-taxi.jpg" %}')">
    <div>
        <a href="/profile"><img class="Logo" src="{% static "img/Logo.png" %}"></a>
        <p class="LogoText">DRONE TAXI</p>
    </div>
    <div class="AuthForm">
        <form class="Form" method="POST" id="authForm"> 
            <p class="Authorized"> АВТОРИЗАЦИЯ </p>
            {% csrf_token %}
            <div class="FormGroup">
                <label for="id_login">Логин</label>
                <br>
                <input type="text" name="login" required id="id_login" value="{{login}}">
            </div>
            <div class="FormGroup">
                <label for="id_password">Пароль</label>
                <br>
                <input type="password" name="password" required id="id_password">
            </div>

            <br>
            <div class="SaveAndEnter">
                <input class="SaveUseraccount" name="remember" type="checkbox">
                <p class="SaveUseraccountText">Запомнить</p>
                <input class="EnterButton" type="submit" value="Войти">
            </div>
        </form>
        <a href="{% url 'registration' %}"><button class="RegistrationButton LogPage" type="submit">Регистрация</button></a>
    </div>
    {% if error %}
    <div class="ErrorBlock">
        <p class="Message">Неверный логин или пароль</p>
    </div>
    {% endif %}
</body>
</html>

DroneTaxi/templates/login/registration.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Drone Taxi - Регистрация</title>
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
</head>
<body class="BodyBackground" style="background-image: url('{% static "img/flying-taxi.jpg" %}')">
    <div>
        <a href="/profile"><img class="Logo" src="{% static "img/Logo.png" %}"></a>
        <p class="LogoText">DRONE TAXI</p>
    </div>
    <header id="app">
        <form class="Form" method="POST">
            {% csrf_token %}
        <table class="UserTable">
            <tr> 
                <td class="UserTD"><p class="HeaderReg">Регистрация</p></td>
            </tr>
            <tr> 
                <td class="UserTD"><p class="Header">Фамилия *</p><input value="{{lastname}}" name="lastname" required></td>
            </tr>
            <tr>
                <td class="UserTD"><p class="Header">Имя *</p><input value="{{firstname}}" name="firstname"required></td>
            </tr>
            <tr> 
                <td class="UserTD"><p class="Header">Отчество </p><input value="{{patronymic}}" name="patronymic"></td>
            </tr>
            <tr>
                <td class="UserTD"><p class="Header">Email *</p><input name="email" value="{{email}}" required></td>
            </tr>
            <tr> 
                <td class="UserTD"><p class="Header">Пароль *</p><input name="password" type="password" value="{{password}}" required></td>
            </tr>
            <tr>
                <td class="UserTD"><p class="Header">Подтвердить пароль *</p><input name="confpassword" type="password" value="{{confpassword}}" required></td>
            </tr>
            <tr>
                <td><input type="submit" class="RegistrationButton" value="Регистрация"></td>
            </tr>
        </table>
        </form>
    </header>
    {% if mailerror or passerror or notmail or smallpass %}
    <div class="ErrorBlock">
        {% if passerror%}
        <p class="Message">Пароли в полях должны совпадать</p>
        {% endif %}
        {% if mailerror%}
        <p class="Message">Данная почта уже используется</p>
        {% endif %}
        {% if notmail%}
        <p class="Message">Неверно задан формат почты</p>
        {% endif %}
        {% if smallpass %}
        <p class="Message">Пароль должен состоять не менее из восьми символов</p>
        {% endif %}
    </div>
    {% endif %}
</body>

</html>